"""
SDN Node Agent - per-node daemon for tunnel management.

Each SDN node runs this agent to:
1. Register with the central controller
2. Receive tunnel configuration updates
3. Apply WireGuard/AmneziaWG configurations locally
4. Monitor tunnel health and report status
5. Handle key rotation events

Can operate in:
- Managed mode: controlled by central controller via API
- Standalone mode: reads local topology/config files
"""

import json
import os
import subprocess
import time
import hashlib
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any, Callable
from threading import Thread, Event

import requests


@dataclass
class TunnelStatus:
    """Status of a single tunnel peer."""
    peer_public_key: str
    endpoint: str
    allowed_ips: List[str]
    latest_handshake: Optional[float] = None
    transfer_rx: int = 0
    transfer_tx: int = 0
    persistent_keepalive: int = 0
    connected: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "peer": self.peer_public_key[:16] + "...",
            "endpoint": self.endpoint,
            "allowed_ips": self.allowed_ips,
            "latest_handshake": self.latest_handshake,
            "transfer_rx": self.transfer_rx,
            "transfer_tx": self.transfer_tx,
            "connected": self.connected,
        }


@dataclass
class NodeStatus:
    """Overall status of this SDN node."""
    node_name: str
    interface: str
    address: str
    listen_port: int
    public_key: str
    peer_count: int
    peers: List[TunnelStatus] = field(default_factory=list)
    uptime_seconds: float = 0
    last_config_update: Optional[float] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "node": self.node_name,
            "interface": self.interface,
            "address": self.address,
            "listen_port": self.listen_port,
            "public_key": self.public_key[:16] + "...",
            "peer_count": self.peer_count,
            "peers": [p.to_dict() for p in self.peers],
            "uptime_seconds": self.uptime_seconds,
            "last_config_update": self.last_config_update,
        }


class NodeAgent:
    """Per-node agent that manages WireGuard/AmneziaWG tunnels.

    The agent applies configurations generated by the controller,
    monitors tunnel health, and reports status back.

    In this prototype, the agent demonstrates the full lifecycle
    including config application, monitoring, and API communication.
    """

    def __init__(
        self,
        node_name: str,
        controller_url: Optional[str] = None,
        config_dir: Optional[Path] = None,
        interface: str = "wg0",
    ):
        self.node_name = node_name
        self.controller_url = controller_url
        self.config_dir = config_dir or Path("./node_configs")
        self.interface = interface
        self._start_time = time.time()
        self._stop_event = Event()
        self._monitor_thread: Optional[Thread] = None
        self._config_hash: Optional[str] = None
        self._status: Optional[NodeStatus] = None
        self._on_status_change: Optional[Callable] = None

    def set_status_callback(self, cb: Callable) -> None:
        """Set a callback for status change notifications."""
        self._on_status_change = cb

    def register_with_controller(self) -> bool:
        """Register this node with the central controller."""
        if not self.controller_url:
            return False

        try:
            # Get our config from controller
            resp = requests.get(
                f"{self.controller_url}/api/v1/configs/{self.node_name}",
                params={"format": "json"},
                timeout=10,
            )
            if resp.status_code == 200:
                self.apply_json_config(resp.json())
                return True
        except requests.RequestException as e:
            print(f"Failed to register with controller: {e}")
        return False

    def apply_json_config(self, config: Dict[str, Any]) -> bool:
        """Apply a JSON-format configuration.

        In production, this would:
        1. Write the config to /etc/wireguard/<interface>.conf
        2. Run `wg syncconf <interface> <(wg-quick strip <interface>)`
        3. Or use `wg set` commands for live updates

        For the prototype, we validate and store the config.
        """
        if "interface" not in config:
            print(f"Invalid config: missing 'interface' section")
            return False

        iface = config["interface"]
        peers = config.get("peers", [])

        # Validate required fields
        required = ["private_key", "address", "listen_port"]
        for field in required:
            if field not in iface:
                print(f"Invalid config: missing '{field}' in interface")
                return False

        # Compute config hash to detect changes
        config_str = json.dumps(config, sort_keys=True)
        new_hash = hashlib.sha256(config_str.encode()).hexdigest()
        if new_hash == self._config_hash:
            return True  # No change

        # In a real deployment, apply the config:
        # 1. Write config file (do this BEFORE setting hash so failure allows retry)
        self.config_dir.mkdir(parents=True, exist_ok=True)
        config_file = self.config_dir / f"{self.interface}.conf"
        self._write_wg_config(config, config_file)

        # 2. Apply via wg-quick or wg syncconf
        applied = self._apply_wireguard_config(config_file)

        # Only cache the hash after successful write + apply
        if applied:
            self._config_hash = new_hash

        # Update status
        self._status = NodeStatus(
            node_name=self.node_name,
            interface=self.interface,
            address=iface["address"],
            listen_port=iface["listen_port"],
            public_key=self._public_key_from_private(
                iface["private_key"]
            ),
            peer_count=len(peers),
            peers=[
                TunnelStatus(
                    peer_public_key=p["public_key"],
                    endpoint=p.get("endpoint", ""),
                    allowed_ips=p.get("allowed_ips", []),
                    persistent_keepalive=p.get("persistent_keepalive", 25),
                )
                for p in peers
            ],
            last_config_update=time.time(),
        )

        if self._on_status_change:
            self._on_status_change(self._status)

        return True

    def apply_config_file(self, config_path: Path) -> bool:
        """Apply a wg-quick compatible config file."""
        if not config_path.exists():
            print(f"Config file not found: {config_path}")
            return False

        # In production: `wg-quick down <interface>` then `wg-quick up <config>`
        # For prototype: validate and parse
        with open(config_path) as f:
            content = f.read()

        self._config_hash = hashlib.sha256(content.encode()).hexdigest()

        # Copy to config dir
        self.config_dir.mkdir(parents=True, exist_ok=True)
        import shutil
        target = self.config_dir / f"{self.interface}.conf"
        shutil.copy(config_path, target)

        self._apply_wireguard_config(target)
        return True

    def start_monitoring(self, interval: float = 10.0) -> None:
        """Start background monitoring thread."""
        if self._monitor_thread and self._monitor_thread.is_alive():
            return

        self._stop_event.clear()
        self._monitor_thread = Thread(
            target=self._monitor_loop,
            args=(interval,),
            daemon=True,
        )
        self._monitor_thread.start()

    def stop_monitoring(self) -> None:
        """Stop the monitoring thread."""
        self._stop_event.set()
        if self._monitor_thread:
            self._monitor_thread.join(timeout=5)

    def get_status(self) -> Optional[NodeStatus]:
        """Get the current node status."""
        if self._status:
            self._status.uptime_seconds = time.time() - self._start_time
        return self._status

    def report_status_to_controller(self) -> bool:
        """Report node status to the controller."""
        if not self.controller_url:
            return False

        try:
            status = self.get_status()
            if status:
                resp = requests.post(
                    f"{self.controller_url}/api/v1/nodes/{self.node_name}/status",
                    json=status.to_dict(),
                    timeout=5,
                )
                return resp.status_code == 200
        except requests.RequestException:
            pass
        return False

    def _monitor_loop(self, interval: float) -> None:
        """Background monitoring loop."""
        while not self._stop_event.is_set():
            # In production: query `wg show <interface> dump` for live stats
            self._update_peer_stats()
            if self.controller_url:
                self.report_status_to_controller()
            self._stop_event.wait(interval)

    def _update_peer_stats(self) -> None:
        """Query wg for live peer statistics."""
        try:
            result = subprocess.run(
                ["wg", "show", self.interface, "dump"],
                capture_output=True, text=True, timeout=5,
            )
            if result.returncode == 0:
                self._parse_wg_dump(result.stdout)
        except (FileNotFoundError, subprocess.SubprocessError):
            # wg CLI not available (expected in container)
            pass

    def _parse_wg_dump(self, dump: str) -> None:
        """Parse `wg show dump` output to update peer status."""
        if not self._status:
            return

        for line in dump.strip().split("\n")[1:]:  # Skip header
            parts = line.split("\t")
            if len(parts) < 8:
                continue

            peer_key = parts[0]
            for peer_status in self._status.peers:
                if peer_status.peer_public_key == peer_key:
                    peer_status.endpoint = parts[2]
                    peer_status.latest_handshake = (
                        float(parts[4]) if parts[4] != "0" else None
                    )
                    peer_status.transfer_rx = int(parts[5])
                    peer_status.transfer_tx = int(parts[6])
                    peer_status.persistent_keepalive = int(parts[7])
                    peer_status.connected = peer_status.latest_handshake is not None
                    break

    def _write_wg_config(
        self, config: Dict[str, Any], path: Path
    ) -> None:
        """Write a WireGuard config file from JSON config."""
        iface = config["interface"]
        lines = [
            "[Interface]",
            f"PrivateKey = {iface['private_key']}",
            f"Address = {iface['address']}",
            f"ListenPort = {iface['listen_port']}",
            f"MTU = {iface.get('mtu', 1420)}",
        ]

        if iface.get("dns"):
            lines.append(f"DNS = {', '.join(iface['dns'])}")

        for cmd in iface.get("pre_up", []) or []:
            lines.append(f"PreUp = {cmd}")
        for cmd in iface.get("post_up", []) or []:
            lines.append(f"PostUp = {cmd}")
        for cmd in iface.get("pre_down", []) or []:
            lines.append(f"PreDown = {cmd}")
        for cmd in iface.get("post_down", []) or []:
            lines.append(f"PostDown = {cmd}")

        lines.append("")

        for peer in config.get("peers", []):
            lines.append("[Peer]")
            lines.append(f"PublicKey = {peer['public_key']}")
            if peer.get("preshared_key"):
                lines.append(f"PresharedKey = {peer['preshared_key']}")
            if peer.get("endpoint"):
                lines.append(f"Endpoint = {peer['endpoint']}")
            if peer.get("allowed_ips"):
                lines.append(f"AllowedIPs = {', '.join(peer['allowed_ips'])}")
            if peer.get("persistent_keepalive"):
                lines.append(
                    f"PersistentKeepalive = {peer['persistent_keepalive']}"
                )
            lines.append("")

        with open(path, "w") as f:
            f.write("\n".join(lines))

    def _apply_wireguard_config(self, config_path: Path) -> bool:
        """Apply WireGuard config using wg-quick or wg.

        In production, this runs `wg-quick up <config>` or
        `wg syncconf <interface> <(wg-quick strip <config>)`.
        In the container (no NET_ADMIN), this is a no-op that
        validates the config file exists and is readable.
        """
        if not config_path.exists():
            return False

        # Try to apply if we have permissions
        try:
            # Check if interface already exists (may need cleanup)
            subprocess.run(
                ["wg", "show", self.interface],
                capture_output=True, timeout=2,
            )
            # Apply config
            result = subprocess.run(
                ["wg-quick", "up", str(config_path)],
                capture_output=True, text=True, timeout=10,
            )
            if result.returncode == 0:
                return True
            # wg-quick failed — likely no NET_ADMIN
        except (FileNotFoundError, subprocess.SubprocessError):
            pass

        # Config is valid and written — in a real deployment it would be active
        return True

    def update_peer_allowed_ips(
        self, peer_public_key: str, allowed_ips: List[str]
    ) -> bool:
        """Update a peer's AllowedIPs at runtime without restarting the tunnel.

        Uses `wg set <interface> peer <key> allowed-ips <cidrs>` which
        is instantaneous and does NOT drop the connection or re-handshake.

        This is how remote prefix changes propagate: when a gateway
        advertises a new subnet, the controller pushes an AllowedIPs
        update to all peers, and traffic to that subnet starts flowing
        immediately through the existing tunnel.
        """
        try:
            ips_arg = ",".join(allowed_ips)
            result = subprocess.run(
                ["wg", "set", self.interface, "peer", peer_public_key,
                 "allowed-ips", ips_arg],
                capture_output=True, text=True, timeout=5,
            )
            if result.returncode == 0:
                # Update our internal status
                if self._status:
                    for peer_status in self._status.peers:
                        if peer_status.peer_public_key == peer_public_key:
                            peer_status.allowed_ips = allowed_ips
                            break
                return True
            else:
                print(f"wg set failed: {result.stderr}")
                return False
        except FileNotFoundError:
            # wg CLI not available — in prototype mode this is expected
            return True
        except subprocess.SubprocessError as e:
            print(f"Failed to update peer AllowedIPs: {e}")
            return False

    def add_peer_route(
        self, peer_public_key: str, prefix: str
    ) -> bool:
        """Add a single prefix to a peer's AllowedIPs live.

        Gets the current AllowedIPs, appends the new prefix,
        and applies the update atomically via `wg set`.
        When _status is None (config not yet applied), the prefix
        is still added — the peer's existing AllowedIPs in the
        kernel are preserved by querying `wg show` first.
        """
        current_ips = []
        if self._status:
            for ps in self._status.peers:
                if ps.peer_public_key == peer_public_key:
                    current_ips = list(ps.allowed_ips)
                    break

        # If _status is not set, query kernel for current AllowedIPs
        if not self._status:
            current_ips = self._get_kernel_allowed_ips(peer_public_key)

        if prefix not in current_ips:
            current_ips.append(prefix)

        return self.update_peer_allowed_ips(peer_public_key, current_ips)

    def remove_peer_route(
        self, peer_public_key: str, prefix: str
    ) -> bool:
        """Remove a single prefix from a peer's AllowedIPs live."""
        current_ips = []
        if self._status:
            for ps in self._status.peers:
                if ps.peer_public_key == peer_public_key:
                    current_ips = [
                        ip for ip in ps.allowed_ips if ip != prefix
                    ]
                    break

        # If _status is not set, query kernel for current AllowedIPs
        if not self._status:
            current_ips = self._get_kernel_allowed_ips(peer_public_key)
            current_ips = [ip for ip in current_ips if ip != prefix]

        return self.update_peer_allowed_ips(peer_public_key, current_ips)

    def _get_kernel_allowed_ips(self, peer_public_key: str) -> List[str]:
        """Query the WireGuard kernel interface for a peer's current AllowedIPs."""
        try:
            result = subprocess.run(
                ["wg", "show", self.interface, "allowed-ips"],
                capture_output=True, text=True, timeout=5,
            )
            if result.returncode == 0:
                ips = []
                for line in result.stdout.strip().split("\n"):
                    parts = line.split("\t")
                    if len(parts) >= 2 and parts[0].strip() == peer_public_key:
                        ips = [ip.strip() for ip in parts[1].split(",") if ip.strip()]
                        break
                return ips
        except (FileNotFoundError, subprocess.SubprocessError):
            pass
        return []

    def _public_key_from_private(self, private_key: str) -> str:
        """Derive public key from private key using wg CLI."""
        try:
            result = subprocess.run(
                ["wg", "pubkey"],
                input=private_key,
                capture_output=True,
                text=True,
                check=True,
            )
            return result.stdout.strip()
        except (FileNotFoundError, subprocess.SubprocessError):
            return "UNAVAILABLE"
